name: Python Tests
on:
  push:
    branches: [ work ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r lambda_requirements.txt
      - run: pip install -r test/requirements.txt
      - run: pip install pytest boto3
      - run: pytest -q
